import "./globals.css";

export const metadata = {
    title: {
        default: "Khalid Abbas Jan — Senior Full-Stack Developer (SaaS & Canvas)",
        template: "%s | Khalid Abbas Jan"
    },
    description:
        "Senior full-stack developer building multi-tenant SaaS and interactive 2D canvas applications — React, Next.js, Node.js, Fabric.js, Konva.js, and AWS. Fence-industry platforms, estimating, and design tooling.",
    keywords: [
        "Senior Full-Stack Developer",
        "SaaS",
        "React Developer",
        "Next.js",
        "Node.js",
        "Fabric.js",
        "Konva.js",
        "Canvas",
        "TypeScript",
        "AWS",
        "PostgreSQL",
        "MongoDB",
        "Express.js",
        "Full-Stack Developer",
        "Web Developer",
        "JavaScript",
        "HTML5 Canvas",
        "Khalid Abbas Jan"
    ],
    authors: [{ name: "Khalid Abbas Jan" }],
    creator: "Khalid Abbas Jan",
    openGraph: {
        type: "website",
        locale: "en_US",
        url: "https://khalid-abbas-portfolio.vercel.app",
        title: "Khalid Abbas Jan — Senior Full-Stack Developer (SaaS & Canvas)",
        description:
            "Multi-tenant SaaS, interactive 2D canvas tools, React/Next.js, Node.js, AWS — portfolio and experience.",
        siteName: "Khalid Abbas Jan Portfolio",
        images: [
            {
                url: "/assets/images/og-image.png",
                width: 1200,
                height: 630,
                alt: "Khalid Abbas Jan — Senior Full-Stack Developer Portfolio"
            }
        ]
    },
    twitter: {
        card: "summary_large_image",
        title: "Khalid Abbas Jan — Senior Full-Stack Developer",
        description:
            "SaaS, cloud, and interactive 2D canvas tools — React, Next.js, Node.js, Fabric.js, Konva.js, AWS.",
        images: ["/assets/images/og-image.png"],
        creator: "@khalid_abbas_iu"
    },
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1
        }
    },
    verification: {
        google: "your-google-verification-code", // Add your Google Search Console verification
        yandex: "your-yandex-verification-code", // Add if needed
        yahoo: "your-yahoo-verification-code" // Add if needed
    }
};

export const viewport = {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
    userScalable: true,
    themeColor: [
        { media: "(prefers-color-scheme: light)", color: "#ffffff" },
        { media: "(prefers-color-scheme: dark)", color: "#000000" }
    ]
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <head>
            {/* Google Fonts - Optimized Loading */}
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
            <link
                href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600;700&display=swap"
                rel="stylesheet"
            />

            {/* Favicon and Icons - Only reference existing files */}
            <link rel="icon" href="/favicon.ico" sizes="any" />
            {/* Remove references to missing files */}
            {/* Manifest will be auto-generated by Next.js from app/manifest.js */}

            {/* Performance Optimizations */}
            <link rel="dns-prefetch" href="//fonts.googleapis.com" />
            <link rel="dns-prefetch" href="//fonts.gstatic.com" />

            {/* Structured Data for SEO */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "Person",
                        "name": "Khalid Abbas Jan",
                        "jobTitle": "Senior Full-Stack Developer",
                        "description":
                            "Senior full-stack developer building multi-tenant SaaS and interactive 2D canvas applications with React, Next.js, Node.js, Fabric.js, Konva.js, and AWS",
                        "url": "https://khalid-abbas-portfolio.vercel.app",
                        "sameAs": [
                            "https://github.com/Khalid-Abbas-IU",
                            "https://www.linkedin.com/in/khalid-abbas-869831193/",
                            "https://www.fiverr.com/khalid_abbasiu",
                            "https://www.upwork.com/freelancers/~01e48daa9d2ab5861a"
                        ],
                        "knowsAbout": [
                            "JavaScript",
                            "TypeScript",
                            "React",
                            "Next.js",
                            "Node.js",
                            "MongoDB",
                            "PostgreSQL",
                            "Express.js",
                            "Canvas API",
                            "Fabric.js",
                            "Konva.js",
                            "AWS",
                            "Tailwind CSS",
                            "SaaS"
                        ],
                        "alumniOf": {
                            "@type": "Organization",
                            "name": "Your University Name" // Replace with actual university
                        },
                        "address": {
                            "@type": "PostalAddress",
                            "addressLocality": "Rawalpindi",
                            "addressRegion": "Punjab",
                            "addressCountry": "Pakistan"
                        }
                    })
                }}
            />
        </head>
        <body className="font-inter antialiased bg-black text-white min-h-screen overflow-x-hidden">
        {/* NO loading screen in layout - let the page component handle it */}
        <main>
            {children}
        </main>
        </body>
        </html>
    );
}